### ISSUE TITLE
proposal: Better describe what this module does.

### ISSUE THREAD

**Issue by enthus1ast** [AS400JPLPC/nim_termkey#1]
Hi JPLRouge,

it was very hard for me to reason about what your module actually does, by reading the README.md.
I had to skim through the code to see that this is a terminal library with a nice feature set.
(ok nim_termkey gave it away but still).

I think for better visibility, rework your README.md a bit. 👍

**Comment by AS400JPLPC** [comment]
I reworked the introduction, after it is only the base of a Terminal application, TERMCURS allows it to really work as NCURSES or other input control multiple window display etc ... grid, menu ... pure NIM

**Comment by AS400JPLPC** [comment]
> Hi JPLRouge,
> 
> it was very hard for me to reason about what your module actually does, by reading the README.md.
> I had to skim through the code to see that this is a terminal library with a nice feature set.
> (ok nim_termkey gave it away but still).
> 
> I think for better visibility, rework your README.md a bit. +1

**Comment by AS400JPLPC** [comment]
Full change, Nim "terminal" independence, modification and allocation of the handle, I use DUP2 in order not to have competition with the different calls systems, I discovered that with the mqueue, other by I pugé the code for example in the "resetattribute" there is no need to test if gFH is at zeros since already reset to zeros the line before .... etc ...

the purge of the code is due to the simplification and single use for Linux
